/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface SvgramCanvas {
    'content': any;
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SvgramCanvasAttributes extends StencilHTMLAttributes {
    'content'?: any;
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'SvgramCanvas': Components.SvgramCanvas;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'svgram-canvas': Components.SvgramCanvasAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSvgramCanvasElement extends Components.SvgramCanvas, HTMLStencilElement {}
  var HTMLSvgramCanvasElement: {
    prototype: HTMLSvgramCanvasElement;
    new (): HTMLSvgramCanvasElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'svgram-canvas': HTMLSvgramCanvasElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'svgram-canvas': HTMLSvgramCanvasElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
