/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface Sv5Canvas {
    'content': any;
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface Sv5CanvasAttributes extends StencilHTMLAttributes {
    'content'?: any;
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'Sv5Canvas': Components.Sv5Canvas;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'sv5-canvas': Components.Sv5CanvasAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSv5CanvasElement extends Components.Sv5Canvas, HTMLStencilElement {}
  var HTMLSv5CanvasElement: {
    prototype: HTMLSv5CanvasElement;
    new (): HTMLSv5CanvasElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'sv5-canvas': HTMLSv5CanvasElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sv5-canvas': HTMLSv5CanvasElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
